#include "fixture.h"
#include <csetjmp>
#include <iostream>
#include <rex/thread/fiber.h>
#include <stdexcept>
#include <windows.h>

namespace {
PPCContext ctx{};
std::jmp_buf scheduler;
cod3::coroutine_tests::Node* current_node = nullptr;
void GuestTransfer(uint32_t buffer, int value) {
  if (!cod3::coroutines::InterceptLongjmp(buffer, value)) longjmp(scheduler, value ? value : 1);
  throw std::runtime_error("a nonlocal transfer unexpectedly returned");
}
void Complete(uint32_t node, PPCContext&, uint8_t*) {
  if (node != current_node->key) throw std::runtime_error("wrong completion node");
  current_node->done = 1;
  ++current_node->completion_callbacks;
}
void Step(cod3::coroutine_tests::Node& node, bool first,
          rex::thread::Fiber* scheduler_root = nullptr) {
  current_node = &node;
  node.original_context = &ctx;
  auto* base = reinterpret_cast<uint8_t*>(&node);
  cod3::coroutines::ResumeScope scope(ctx, base, node.key, GuestTransfer, Complete,
                                      scheduler_root);
  const uint32_t root_host_fpscr =
      ctx.fpscr.getcsr() & ~PPCFPSCRRegister::GuestMask;
  const PPCContext env = ctx;
  cod3::coroutines::NoteSetjmp(cod3::coroutines::kSchedulerBuffer);
  if (setjmp(scheduler) != 0) {
    ctx = env; // Same landing restore generated by ReXGlue.
    ctx.fpscr.restoreGuestBits(ctx.fpscr.csr);
    node.host_fp_ok &=
        (ctx.fpscr.getcsr() & ~PPCFPSCRRegister::GuestMask) == root_host_fpscr;
    return;
  }
  if (first) {
    cod3::coroutines::StartClosure(ctx, base, cod3::coroutine_tests::FixtureClosure);
    Complete(node.key, ctx, base); // Original initial-call completion tail.
  } else {
    // Independent original-opcode fixtures provide the state AFTER the real
    // guest400-frame restore. The bridge must transfer it unchanged.
    cod3::coroutine_tests::PutState(ctx, cod3::coroutine_reference_vectors::kVectors[node.vector].restore_expected);
    cod3::coroutines::ResumeRestored();
  }
}
bool Check(bool value, const char* name) {
  std::cout << (value ? "PASS " : "FAIL ") << name << '\n';
  return value;
}
}
int main() {
  using namespace cod3;
  bool ok = true;
  ctx.fpscr.InitHost();
  coroutine_tests::FixtureSetTransfer(GuestTransfer);
  for (size_t i=0; i<std::size(coroutine_reference_vectors::kVectors); ++i) {
    coroutine_tests::Node node;
    node.key = 0xAA000000 + uint32_t(i)*0x100;
    node.vector = i;
    node.exit_instead = (i & 1) != 0;
    Step(node, true);
    ok &= node.saves == 1 && node.resumes == 0 && coroutines::ParkedCount() == 1;
    Step(node, false);
    ok &= node.saves == 2 && node.resumes == 1;
    Step(node, false);
    ok &= node.saves == 2 && node.resumes == 2 && node.done == 1 && node.fallthrough == 0 &&
          node.capture_cleanup == 2 && node.script_cleanup == 1 && node.identity_ok && node.fp_ok &&
          node.state_ok && node.native_locals_ok && node.host_fp_ok &&
          node.completion_callbacks == (node.exit_instead ? 0 : 1);
    coroutines::Destroy(node.key);
  }
  ok &= Check(ok, "32 independent reference states survive two yields/resumes, normal return and nonlocal completion");
  coroutine_tests::Node cancelled;
  cancelled.key = 0xAA100000;
  Step(cancelled, true);
  const auto before = ctx.r31.u64;
  coroutines::BeforeModuleUnload(0x89000000);
  ok &= Check(cancelled.script_cleanup == 1 && cancelled.resumes == 0 &&
              coroutines::ParkedCount() == 0 && ctx.r31.u64 == before,
              "parked mission cancellation unwinds native frames before unload and preserves scheduler context");
  coroutine_tests::Node invalid;
  invalid.key = 0xAA200000;
  invalid.bad_cross_fiber_jump = true;
  coroutines::NoteSetjmp(0x12345678);
  bool rejected = false;
  try { Step(invalid, true); }
  catch (const std::runtime_error&) { rejected = true; }
  coroutines::Destroy(invalid.key);
  ok &= Check(rejected && invalid.script_cleanup == 1,
              "unsupported cross-fiber longjmp fails through the scheduler without jumping to a foreign stack");
  coroutines::ReleaseThread();
  ok &= Check(!IsThreadAFiber(), "bridge-owned thread-to-fiber conversion is released after all tasks");
  // ReXGlue XThread converts its thread with the SDK's plain Fiber wrapper
  // before calling the title. Match that borrowed, non-FLOAT_SWITCH root.
  auto* borrowed_root = rex::thread::Fiber::ConvertCurrentThread();
  if (!borrowed_root) return 2;
  for (size_t i=0; i<std::size(coroutine_reference_vectors::kVectors); ++i) {
    coroutine_tests::Node node;
    node.key = 0xAA300000 + uint32_t(i)*0x100;
    node.vector = i;
    Step(node, true, borrowed_root);
    Step(node, false, borrowed_root);
    Step(node, false, borrowed_root);
    ok &= node.resumes == 2 && node.state_ok && node.fp_ok && node.identity_ok &&
          node.host_fp_ok && node.script_cleanup == 1;
    coroutines::Destroy(node.key);
  }
  coroutines::ReleaseThread();
  ok &= Check(IsThreadAFiber(),
              "borrowed SDK-style root fiber survives 32 reference cases and bridge release");
  borrowed_root->Destroy();
  ok &= Check(!IsThreadAFiber(), "test-owned borrowed root cleanup");
  return ok ? 0 : 1;
}
