[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$workspace = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$mapPath = Join-Path $workspace 'analysis/cod3-allmodule-coroutine-sites.json'
$map = Get-Content -LiteralPath $mapPath -Raw | ConvertFrom-Json
if ($map.module_count -ne 15 -or $map.verified_module_count -ne 15 -or $map.capture_count -ne 45) {
    throw 'Expected the independently verified 15-module, 45-capture map.'
}
$mainHash = (Get-FileHash -LiteralPath (Join-Path $workspace 'game/cod3/default.xex') -Algorithm SHA256).Hash
if ($mainHash -ne '2944EEC7D1231AD6798B5F9F8ADF8855F5E489296B22EAB45B27A577CEE23692') {
    throw 'The main XEX differs from the opcode-verified build.'
}
$generated = Join-Path $PSScriptRoot 'generated'
[IO.Directory]::CreateDirectory($generated) | Out-Null
$cmake = @('# Verified original-XEX capture entry wrappers; generated by Prepare.ps1.')
foreach ($module in $map.modules) {
    if ($module.status -ne 'verified' -or $module.image_base -ne '0x89000000') {
        throw 'An unverified or differently based mission appears in the map.'
    }
    $moduleHash = (Get-FileHash -LiteralPath (Join-Path $workspace $module.input_xex) -Algorithm SHA256).Hash
    if ($moduleHash -ne $module.input_sha256) { throw "Mission XEX differs: $($module.guest_path)" }
    $stem = [IO.Path]::GetFileNameWithoutExtension($module.guest_path)
    if ($module.captures.Count -ne 3) { throw "Expected 3 captures for $stem" }
    $lines = @('#include <rex/hook.h>', '#include "cod3_coroutines.h"', '')
    foreach ($capture in $module.captures) {
        if (-not $capture.full_body_verification.relative_global_layout_matches -or
            -not $capture.full_body_verification.all_non_address_bits_match) {
            throw 'A capture body lacks the complete original-opcode verification.'
        }
        $symbol = 'sub_' + $capture.address.Substring(2).ToUpperInvariant()
        $lines += "REX_EXTERN(__imp__$symbol);"
        $lines += "REX_HOOK_RAW($symbol) { cod3::coroutines::Capture(ctx, base, __imp__$symbol, 0x89000000); }"
    }
    [IO.File]::WriteAllText((Join-Path $generated "capture_$stem.cpp"), ($lines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
    $cmake += ('cod3_attach_capture_hooks(cod3_pc_' + $stem + ' "${CMAKE_CURRENT_LIST_DIR}/capture_' + $stem + '.cpp")')
}
[IO.File]::WriteAllText((Join-Path $generated 'capture_targets.cmake'), ($cmake -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
# The SDK source is tools/rexglue-source in the workspace and sdk-source in a
# released package. The template is the same file in both, and the anchored
# replacements below refuse anything else.
$templateSource = $null
foreach ($candidate in @('tools/rexglue-source', 'sdk-source')) {
    $probe = Join-Path $workspace "$candidate/resources/templates/codegen/pch_h.inja"
    if (Test-Path -LiteralPath $probe -PathType Leaf) { $templateSource = $probe; break }
}
if (-not $templateSource) { throw 'The SDK codegen PCH template was not found under tools/rexglue-source or sdk-source.' }
$template = [IO.File]::ReadAllText($templateSource)
$setjmp = '#define ppc_setjmp(guest_buf_addr) (setjmp(::get_jmp_buf_map()[(guest_buf_addr)]))'
$longjmp = '[[noreturn]] inline void ppc_longjmp(u32 guest_buf_addr, int val) {'
foreach ($expected in @('#include <unordered_map>', $setjmp, $longjmp)) {
    if ([regex]::Matches($template, [regex]::Escape($expected)).Count -ne 1) {
        throw 'Pinned SDK PCH template changed; review the coroutine overlay.'
    }
}
$template = $template.Replace('#include <unordered_map>', "#include <unordered_map>`n#include <cod3_coroutines.h>`nvoid Cod3CoroutineResumeRestored();")
$template = $template.Replace($setjmp, '#define ppc_setjmp(guest_buf_addr) (cod3::coroutines::NoteSetjmp(guest_buf_addr), setjmp(::get_jmp_buf_map()[(guest_buf_addr)]))')
$template = $template.Replace($longjmp, $longjmp + "`n  cod3::coroutines::InterceptLongjmp(guest_buf_addr, val);")
$templateDirectory = Join-Path $PSScriptRoot 'templates/codegen'
[IO.Directory]::CreateDirectory($templateDirectory) | Out-Null
[IO.File]::WriteAllText((Join-Path $templateDirectory 'pch_h.inja'), $template, [Text.UTF8Encoding]::new($false))
[ordered]@{
    generated_utc = [DateTime]::UtcNow.ToString('o')
    verified_map_sha256 = (Get-FileHash -LiteralPath $mapPath -Algorithm SHA256).Hash
    original_template_sha256 = (Get-FileHash -LiteralPath $templateSource -Algorithm SHA256).Hash
    overlay_template_sha256 = (Get-FileHash -LiteralPath (Join-Path $templateDirectory 'pch_h.inja') -Algorithm SHA256).Hash
    capture_wrappers = 45
    scheduler_buffer = '0x829EB1C0'
} | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $PSScriptRoot 'prepared.json') -Encoding utf8
Write-Host 'Prepared 45 verified capture wrappers and the local SDK PCH overlay. No app or SDK files modified.'
