#requires -Version 5.1
<#
.SYNOPSIS
    Produces integration/xenon/generated/thunks.generated.inl from the user's
    own copy of the game.

.DESCRIPTION
    Two guest functions cross the SDK ABI through a reviewed adapter. Their
    bodies are generated by XenonRecomp from the game executable, so they are
    derived from the game and are never shipped in a package: the recipient
    regenerates them from their own legally obtained copy, which is what this
    script does.

    It performs exactly the CPU part of scripts/prepare-cod3-pc.ps1:

        1. build XenonRecomp and XenonAnalyse (MIT) if they are not built yet
        2. analyse the title image and the Xenon helper tables
        3. run XenonAnalyse and XenonRecomp over default.xex
        4. extract the two reviewed thunk bodies, verifying their opcodes and
           their generated text against the recorded expectations

    Step 4 refuses anything it does not recognise, so a different game revision
    stops here rather than silently linking unreviewed generated code.
#>
[CmdletBinding()]
param(
    [string]$Root,
    [int]$Jobs = [Environment]::ProcessorCount,
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$here = $PSScriptRoot
if (-not $Root) { $Root = [IO.Path]::GetFullPath((Join-Path $here '..\..')) }
$Root = [IO.Path]::GetFullPath($Root)

$thunks = Join-Path $Root 'integration\xenon\generated\thunks.generated.inl'
if ((Test-Path -LiteralPath $thunks -PathType Leaf) -and -not $Force) {
    Write-Host "Xenon bridge is already generated: $thunks"
    exit 0
}

$xex = Join-Path $Root 'game\cod3\default.xex'
if (-not (Test-Path -LiteralPath $xex -PathType Leaf)) {
    throw "The game executable is missing: $xex. Extract your own copy of the game first."
}

# The compilers are only needed to build XenonRecomp; a package carries it
# built, so the toolchain environment is set up in that branch alone.
$toolchainScript = Join-Path $Root 'scripts\toolchain-env.ps1'

# --- Python -----------------------------------------------------------------
# The analysis scripts are stdlib-only. A package normally has no interpreter,
# but the toolchain provisioner leaves uv behind, which supplies one.
$pythonExe = $null
$pythonPrefix = @()
# A candidate has to actually start: a virtual environment copied from another
# machine has a python.exe that only says "No Python at ...".
foreach ($candidate in @(
    (Join-Path $Root 'tools\toolchain\bootstrap-python\python.exe'),
    (Join-Path $Root 'tools\toolchain\bootstrap-python\Scripts\python.exe'))) {
    if (-not (Test-Path -LiteralPath $candidate -PathType Leaf)) { continue }
    & $candidate -c "import sys" 2>$null
    if ($LASTEXITCODE -eq 0) { $pythonExe = $candidate; break }
}
if (-not $pythonExe) {
    $systemPython = Get-Command python -ErrorAction SilentlyContinue
    if ($systemPython -and ((& $systemPython.Source --version 2>&1 | Out-String) -match 'Python\s+3\.\d')) {
        $pythonExe = $systemPython.Source
    }
}
if (-not $pythonExe) {
    $uv = Join-Path $Root 'tools\uv\uv.exe'
    if (-not (Test-Path -LiteralPath $uv -PathType Leaf)) {
        $found = Get-Command uv -ErrorAction SilentlyContinue
        if ($found) { $uv = $found.Source } else { $uv = $null }
    }
    if (-not $uv) {
        throw 'Python is required. Run tools/toolchain-provision/Install-Toolchain.ps1 first; it installs uv, which provides one.'
    }
    $pythonExe = $uv
    # analyze-title-image.py decrypts and hashes the title image; uv fetches
    # these two packages into a throwaway environment for the run.
    $pythonPrefix = @('run', '--python', '3.12', '--with', 'xxhash', '--with', 'cryptography')
}
else {
    # A real interpreter: make sure the two non-stdlib imports resolve. The
    # package carries them in analysis/title-python, which the analysis
    # scripts put on their path themselves, so the check looks there too and
    # nothing is fetched from PyPI.
    $titlePython = Join-Path $Root 'analysis\title-python'
    $check = "import sys; sys.path.insert(0, sys.argv[1]); import xxhash, cryptography"
    & $pythonExe -c $check $titlePython 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host 'Installing the two Python packages the image analysis needs'
        & $pythonExe -m pip install --disable-pip-version-check --quiet xxhash cryptography
        if ($LASTEXITCODE -ne 0) { throw 'Could not install the xxhash and cryptography packages.' }
    }
}
Write-Host "Python: $pythonExe $($pythonPrefix -join ' ')"

# --- XenonRecomp ------------------------------------------------------------
$xenonRoot = Join-Path $Root 'tools\XenonRecomp'
if (-not (Test-Path -LiteralPath (Join-Path $xenonRoot 'CMakeLists.txt') -PathType Leaf)) {
    throw "XenonRecomp sources are missing: $xenonRoot"
}
$xenonBuild = Join-Path $xenonRoot 'out\build\windows-release'
$analyse = Join-Path $xenonBuild 'XenonAnalyse\XenonAnalyse.exe'
$recomp = Join-Path $xenonBuild 'XenonRecomp\XenonRecomp.exe'
$cmake = Join-Path $Root 'tools\cmake\bin\cmake.exe'
if (-not (Test-Path -LiteralPath $cmake -PathType Leaf)) { $cmake = 'cmake' }

if (-not (Test-Path -LiteralPath $analyse -PathType Leaf) -or -not (Test-Path -LiteralPath $recomp -PathType Leaf)) {
    if (-not (Test-Path -LiteralPath $toolchainScript -PathType Leaf)) { throw "Toolchain script is missing: $toolchainScript" }
    . $toolchainScript -Quiet
    Write-Host ''
    Write-Host '=== Building XenonRecomp ==='
    & $cmake -S $xenonRoot -B $xenonBuild -G Ninja -DCMAKE_BUILD_TYPE=Release `
        "-DCMAKE_C_COMPILER=clang-cl" "-DCMAKE_CXX_COMPILER=clang-cl"
    if ($LASTEXITCODE -ne 0) { throw "XenonRecomp configure failed (exit $LASTEXITCODE)." }
    & $cmake --build $xenonBuild --parallel $Jobs
    if ($LASTEXITCODE -ne 0) { throw "XenonRecomp build failed (exit $LASTEXITCODE)." }
    foreach ($tool in @($analyse, $recomp)) {
        if (-not (Test-Path -LiteralPath $tool -PathType Leaf)) { throw "Build finished but $tool is missing." }
    }
}

# --- CPU preparation --------------------------------------------------------
$logs = Join-Path $Root 'logs'
New-Item -ItemType Directory -Path $logs -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $Root 'analysis\title-xenon-generated') -Force | Out-Null

Push-Location -LiteralPath $Root
try {
    function ConvertTo-CommandLine([string[]]$Arguments) {
        $parts = foreach ($argument in $Arguments) {
            if ($argument -match '[\s"]') { '"' + ($argument -replace '"', '\"') + '"' } else { $argument }
        }
        return ($parts -join ' ')
    }

    function Invoke-Stage([string]$Name, [string]$Program, [string[]]$Arguments) {
        Write-Host ''
        Write-Host "=== $Name ==="
        $log = Join-Path $logs "prepare-$Name.log"
        # Drive the child process directly. PowerShell's own redirection sets
        # StandardOutputEncoding on the child, which these tools reject when
        # the host itself was started with a redirected console - exactly the
        # case when the launcher runs this from its rebuild window.
        $info = New-Object System.Diagnostics.ProcessStartInfo
        $info.FileName = $Program
        $info.Arguments = ConvertTo-CommandLine $Arguments
        $info.WorkingDirectory = $Root
        $info.UseShellExecute = $false
        $info.RedirectStandardOutput = $true
        $info.RedirectStandardError = $true
        # Smart App Control refuses freshly built, unsigned executables. The
        # block is sometimes lifted a short while after the first attempt, so
        # retry once before reporting it as what it is.
        $process = $null
        for ($attempt = 1; $attempt -le 2; $attempt++) {
            try {
                $process = [System.Diagnostics.Process]::Start($info)
                break
            } catch {
                $message = $_.Exception.Message
                $blocked = $message -match 'application control|Smart App|управлени[ея] приложени'
                if (-not $blocked -or $attempt -eq 2) {
                    if ($blocked) {
                        throw @"
Windows blocked a freshly built tool: $Program

This is Smart App Control, which refuses unsigned executables. It is a Windows
security setting, so the decision is yours: "Windows Security" ->
"App & browser control" -> "Smart App Control". Turning it off is irreversible.
The block sometimes lifts by itself a few minutes after the first attempt, so
running the rebuild again later may simply work.

Original message: $message
"@
                    }
                    throw
                }
                Write-Host '  blocked by Windows application control, retrying in 20 s'
                Start-Sleep -Seconds 20
            }
        }
        $stdout = $process.StandardOutput.ReadToEnd()
        $stderr = $process.StandardError.ReadToEnd()
        $process.WaitForExit()
        $status = $process.ExitCode
        [IO.File]::WriteAllText($log, $stdout + $stderr, (New-Object Text.UTF8Encoding($false)))
        if ($status -ne 0) { throw "$Name failed (exit $status). See $log" }
        Write-Host "  ok, log: $log"
    }

    # The image analysis reads the XEX loader key out of the SDK source, which
    # sits at sdk-source in a package and at tools/rexglue-source in the
    # workspace.
    $sdkSource = 'tools/rexglue-source'
    if (-not (Test-Path -LiteralPath (Join-Path $Root 'tools\rexglue-source\src\system\xex_module.cpp') -PathType Leaf)) {
        if (Test-Path -LiteralPath (Join-Path $Root 'sdk-source\src\system\xex_module.cpp') -PathType Leaf) {
            $sdkSource = 'sdk-source'
        } else {
            throw 'The SDK source is missing; it carries the XEX loader key definition the image analysis needs.'
        }
    }
    Invoke-Stage 'image' $pythonExe ($pythonPrefix + @('scripts/analyze-title-image.py', 'game/cod3/default.xex', '--sdk-source', $sdkSource, '--out-prefix', 'analysis/title-default-image'))
    Invoke-Stage 'helpers' $pythonExe ($pythonPrefix + @('scripts/analyze-title-xenon.py'))
    Invoke-Stage 'xenon-analysis' $analyse @('game/cod3/default.xex', 'analysis/xenon-switch-tables.toml')
    Invoke-Stage 'xenon-codegen' $recomp @('cod3-pc/config/xenon-main.toml', 'tools/XenonRecomp/XenonUtils/ppc_context.h')

    Write-Host ''
    Write-Host '=== Extracting the two reviewed thunks ==='
    $extract = Join-Path $Root 'integration\xenon\extract-generated-thunks.ps1'
    & $extract -GeneratedDirectory (Join-Path $Root 'analysis\title-xenon-generated')
} finally {
    Pop-Location
}

if (-not (Test-Path -LiteralPath $thunks -PathType Leaf)) {
    throw "Extraction finished but $thunks is missing."
}
Write-Host ''
Write-Host "Generated: $thunks"
Write-Host ("SHA256: {0}" -f (Get-FileHash -LiteralPath $thunks -Algorithm SHA256).Hash)
